#pragma once

enum {
    BOOT_MODE = 0,
    UPDATE_MODE
};

enum {
    BM_GET_IMKEY_FAILED = 1,
    BM_TPM_DEC_FAILED=2,
    BM_GET_UUID_FAILED=3,
    BM_DEC_PARTITIONKEY_FAILED=4,
    BM_MOUNT_FAILED=5,
    BM_TPM_FAILED=6,
    BM_REGISTER_CHECK_FAILED=7,
    UM_USB_CHECK_FAILED=8,
	UM_XIMAGE_NOT_FOUND=9,
	UM_GET_MD5_FAILED=10,
	UM_CHECK_MD5_FAILED=11,
    UM_XIMAGE_SAME_MD5=12,
    UM_XIMAGE_RM_FAILED=13,
    M_XIMAGE_COPY_FAILED=14,

};
