#pragma once

enum {
    BOOT_MODE = 0,
    UPDATE_MODE
};

enum {
    BM_GET_IMKEY_FAILED = 1,
    BM_TPM_DEC_FAILED,
    BM_GET_UUID_FAILED,
    BM_DEC_PARTITIONKEY_FAILED,
    BM_MOUNT_FAILED,
    BM_TPM_FAILED,
    BM_REGISTER_CHECK_FAILED,
    UM_USB_CHECK_FAILED,
	UM_XIMAGE_NOT_FOUND,
    UM_XIMAGE_MOUNT_ERRER,
    UM_XIMAGE_UNMOUNT_ERRER,
	UM_GET_SHA1_FAILED,
	UM_CHECK_SHA1_FAILED,
    UM_XIMAGE_SAME_SHA1,
    UM_XIMAGE_RM_FAILED,
    UM_XIMAGE_COPY_FAILED,
    OTHER_FAILED,
};
