#pragma once

enum {
    BOOT_MODE = 0,
    UPDATE_MODE
};

enum {
    BM_GET_IMKEY_FAILED = 1,
    BM_TPM_DEC_FAILED,
    BM_GET_UUID_FAILED,
    BM_DEC_PARTITIONKEY_FAILED,
    BM_MOUNT_FAILED,
    BM_TPM_FAILED,
    BM_REGISTER_CHECK_FAILED,
    UM_USB_CHECK_FAILED,
	UM_XIMAGE_NOT_FOUND,
	UM_GET_MD5_FAILED,
	UM_CHECK_MD5_FAILED,
    UM_XIMAGE_SAME_MD5,
    UM_XIMAGE_RM_FAILED,
    UM_XIMAGE_COPY_FAILED,
    OTHER_FAILED,

};
